name: Count It CI

on:
  push:
    paths:
      - 'count_it/**'
  pull_request:
    paths:
      - 'count_it/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.12']  # tests OK sur versions récentes

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle

      - name: PEP8 on 0-count.py
        working-directory: count_it
        run: pycodestyle 0-count.py

      - name: Ensure README exists and not empty
        working-directory: count_it
        run: test -s README.md

      - name: Check shebang and module docstring
        working-directory: count_it
        run: |
          head -n 1 0-count.py | grep -q '#!/usr/bin/python3'
          grep -q '"""' 0-count.py

      - name: Run tests (make if available, else unittest)
        working-directory: count_it
        run: |
          if [ -f Makefile ]; then
            make
          else
            python -m unittest -v
          fi

      # Optionnel : exécuter explicitement chaque suite
      - name: Run explicit suites (optional)
        if: always()
        working-directory: count_it
        run: |
          python -m unittest -v test_unit_0_count.py
          python -m unittest -v test_integration_0_count.py
          python -m unittest -v test_requirements_0_count.py
          python -m unittest -v test_meta_0_count.py
