name: Infinite Multiplication CI

on:
  push:
    branches: ["**"]                           # ou ["main"]
    paths:
      - "infinite_multiplication/**"           # code du projet
      - ".github/workflows/infinite_multiplication.yml"  # modif du workflow
  pull_request:
    branches: ["**"]
    paths:
      - "infinite_multiplication/**"
  workflow_dispatch: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infinite_multiplication
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools + ltrace + Betty
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ltrace git
          git clone https://github.com/holbertonschool/Betty.git /tmp/Betty
          sudo install -m 0755 /tmp/Betty/betty-style.pl /usr/local/bin/betty-style.pl
          sudo install -m 0755 /tmp/Betty/betty-doc.pl   /usr/local/bin/betty-doc.pl

      - name: Ensure mandatory files exist
        run: |
          test -s 0-mul.c
          test -s _putchar.c
          test -s mul.h
          test -s README.md || { echo "README.md missing"; true; }

      - name: Compile program (Makefile if present)
        run: |
          if [ -f Makefile ]; then
            make re
          else
            gcc -Wall -Wextra -Werror -pedantic -std=gnu89 0-mul.c _putchar.c -o mul
          fi

      - name: Run tests (run BOTH if present)
        run: |
          set -euo pipefail
          ran=0

          # C harness
          if [ -f test0b-mul.c ]; then
            gcc -Wall -Wextra -Werror -pedantic -std=gnu89 test0b-mul.c -o test_mul_c
            ./test_mul_c
            ran=1
          fi

          # Bash or C in test0-mul.c
          if [ -f test0-mul.c ]; then
            if head -n1 test0-mul.c | grep -q '#!/usr/bin/env bash'; then
              chmod +x test0-mul.c
              ./test0-mul.c ./mul
            else
              gcc -Wall -Wextra -Werror -pedantic -std=gnu89 test0-mul.c -o test_mul
              ./test_mul
            fi
            ran=1
          fi

          # Optional tests.sh
          if [ -f tests.sh ]; then
            chmod +x tests.sh
            ./tests.sh ./mul
            ran=1
          fi

          if [ "$ran" -eq 0 ]; then
            echo "No tests found"; exit 1
          fi

      - name: Scoreboard checks
        run: |
          set -euo pipefail
          [[ "$(./mul 123456789 987654321)" == "121932631112635269" ]]
          [[ "$(./mul 000000 42)" == "0" ]]
          set +e
          ./mul 123 12x >/tmp/out 2>/dev/null; rc=$?
          set -e
          grep -qx "Error" /tmp/out
          [ $rc -eq 98 ]
          ./mul 10 98 | grep -qx "980"

      - name: ltrace sanity (informational)
        run: |
          sudo ltrace -f -o ltrace.txt ./mul 123 456 >/dev/null || true
          head -n 40 ltrace.txt || true
          if grep -E "(system|popen|execv|fork)" ltrace.txt; then
            echo "Disallowed call found"; exit 1
          fi

      - name: Betty coding style
        run: |
          betty-style.pl 0-mul.c mul.h || true
          betty-doc.pl   0-mul.c       || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: infinite_multiplication-artifacts
          path: |
            infinite_multiplication/mul
            infinite_multiplication/test_mul
            infinite_multiplication/test_mul_c
            infinite_multiplication/ltrace.txt
          if-no-files-found: ignore
