name: Island Perimeter CI

on:
  push:
    paths:
      - "island_perimeter/**"
      - ".github/workflows/island_perimeter.yml"
  pull_request:
    paths:
      - "island_perimeter/**"
      - ".github/workflows/island_perimeter.yml"

jobs:
  tests:
    name: Island Perimeter CI / Lint + Tests (Python 3.10+, Ubuntu 22.04)
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pep8

      - name: Verify required files
        run: |
          test -d island_perimeter || (echo "Missing island_perimeter directory" && exit 1)
          test -f README.md || (echo "Missing README.md" && exit 1)
          test -f island_perimeter/0-island_perimeter.py || (echo "Missing 0-island_perimeter.py" && exit 1)
          test -f island_perimeter/0-main.py || (echo "Missing 0-main.py" && exit 1)

      - name: Verify file format and shebang
        run: |
          head -n1 island_perimeter/0-island_perimeter.py | grep -qx '#!/usr/bin/python3' || (echo "Bad shebang" && exit 1)
          tail -c1 island_perimeter/0-island_perimeter.py | od -An -t x1 | grep -q '0a' || (echo "No newline at end of file" && exit 1)
          if grep -nE '^\s*(from|import)\s+' island_perimeter/0-island_perimeter.py; then
            echo "No imports allowed!"
            exit 1
          fi

      - name: Run PEP8 style check
        run: |
          pep8 --show-source --show-pep8 island_perimeter/0-island_perimeter.py island_perimeter/0-main.py

      - name: Run unittest
        run: |
          python3 -m unittest discover -s island_perimeter/tests -p "test_*unittest.py" -v

      - name: Run pytest
        run: |
          pytest -v island_perimeter/tests
